using Orleans.Dataflow.Definition;
using Orleans.Dataflow.Identity;
using Orleans.Dataflow.Serialization;

namespace Orleans.Dataflow.Tests.Serialization;

/// <summary>
/// The catalogs the golden fixtures under <c>tests/Orleans.Dataflow.Tests/Fixtures</c> pin.
/// </summary>
/// <remarks>
/// <para>
/// A golden test is only worth its bytes when the catalog it compares against is built here, in code,
/// rather than decoded from the fixture it is checking. Building it in code is what makes a change in the
/// writer show up as a byte difference instead of quietly changing both sides of the comparison.
/// </para>
/// <para>
/// The fixture file itself was written by hand from the catalog envelope table in the design document,
/// not by running the writer over these catalogs. A file generated by the code it pins would only prove
/// that the code agrees with itself; a file transcribed from the specification proves that the code
/// agrees with the specification.
/// </para>
/// </remarks>
internal static class FixtureCatalogs
{
    /// <summary>The file name of the minimal catalog fixture.</summary>
    internal const string MinimalFileName = "minimal-catalog.v1.json";

    /// <summary>
    /// Builds the fixture catalog: one specification declaring all three port kinds and a required
    /// capability, and one declaring nothing but its stage and parameter contract.
    /// </summary>
    /// <returns>The fixture catalog.</returns>
    /// <remarks>
    /// The specifications are supplied in an order the canonical one reverses, so the fixture bytes also
    /// pin that ordering happens at construction. The minimal specification's empty lists pin that an
    /// empty array is written as an empty array rather than omitted, and the rich one pins both boolean
    /// flags in both states.
    /// </remarks>
    internal static StageCatalog Minimal() => StageCatalog.Create([Mapper(), Sink()]);

    /// <summary>
    /// Builds the fixture catalog from specifications supplied in the other order.
    /// </summary>
    /// <returns>A catalog equal, element for element, to <see cref="Minimal"/>.</returns>
    /// <remarks>
    /// Canonical order is a property of the catalog, not of the caller's arguments. Serializing this
    /// catalog and the one above must produce the same bytes, or order insensitivity stops where
    /// serialization begins.
    /// </remarks>
    internal static StageCatalog MinimalFromPermutedInputs() =>
        StageCatalog.Create([Sink(), MapperFromPermutedPorts()]);

    /// <summary>
    /// Builds the fixture catalog with a parameter validator on every specification.
    /// </summary>
    /// <returns>A catalog whose specifications declare exactly what <see cref="Minimal"/> declares.</returns>
    /// <remarks>
    /// A validator is behavior, is never serialized, and therefore cannot change one byte of the
    /// catalog's identity. This catalog exists to state that limit as an executable fact rather than as a
    /// sentence in a document.
    /// </remarks>
    internal static StageCatalog MinimalWithValidators() =>
        StageCatalog.Create(
            [
                StageSpecification.Create(
                    MapperStage,
                    MapperParameters,
                    MapperInputs(),
                    MapperOutputs(),
                    MapperResults(),
                    [CapabilityToken.Nondeployable],
                    new FixtureValidator("the mapper payload is refused")),
                StageSpecification.Create(
                    SinkStage,
                    SinkParameters,
                    parameterValidator: new FixtureValidator("the sink payload is refused")),
            ]);

    /// <summary>Gets the stage reference of the rich fixture specification.</summary>
    private static StageRef MapperStage =>
        StageRef.Create(ProviderId.Create("orleans-core"), StageId.Create("map-async"), 2);

    /// <summary>Gets the stage reference of the minimal fixture specification.</summary>
    private static StageRef SinkStage =>
        StageRef.Create(ProviderId.Create("contoso-sinks"), StageId.Create("to-table"), 1);

    /// <summary>Gets the parameter contract of the rich fixture specification.</summary>
    private static ContractReference MapperParameters =>
        ContractReference.Create(ContractId.Create("map-parameters"), 3);

    /// <summary>Gets the parameter contract of the minimal fixture specification.</summary>
    private static ContractReference SinkParameters =>
        ContractReference.Create(ContractId.Create("table-sink-parameters"), 1);

    /// <summary>Builds the rich fixture specification.</summary>
    /// <returns>A stage with a required input, an optional input, a consumed output, an ignorable
    /// output, a result port, and a required capability.</returns>
    private static StageSpecification Mapper() =>
        StageSpecification.Create(
            MapperStage,
            MapperParameters,
            MapperInputs(),
            MapperOutputs(),
            MapperResults(),
            [CapabilityToken.Nondeployable]);

    /// <summary>Builds the rich fixture specification from ports supplied in the other order.</summary>
    /// <returns>A specification equal to <see cref="Mapper"/>.</returns>
    private static StageSpecification MapperFromPermutedPorts() =>
        StageSpecification.Create(
            MapperStage,
            MapperParameters,
            [Input("side", "lookup-table", 1, isOptional: true), Input("in", "order", 1, isOptional: false)],
            [
                Output("trace", "trace-event", 1, isIgnorable: true),
                Output("out", "order-summary", 3, isIgnorable: false),
            ],
            MapperResults(),
            [CapabilityToken.Nondeployable]);

    /// <summary>Builds the minimal fixture specification.</summary>
    /// <returns>A stage that declares no port and requires no capability.</returns>
    private static StageSpecification Sink() =>
        StageSpecification.Create(SinkStage, SinkParameters);

    /// <summary>Builds the input ports of the rich fixture specification.</summary>
    /// <returns>One required and one optional input port.</returns>
    private static InputPortSpecification[] MapperInputs() =>
        [Input("in", "order", 1, isOptional: false), Input("side", "lookup-table", 1, isOptional: true)];

    /// <summary>Builds the output ports of the rich fixture specification.</summary>
    /// <returns>One consumed and one ignorable output port.</returns>
    private static OutputPortSpecification[] MapperOutputs() =>
        [
            Output("out", "order-summary", 3, isIgnorable: false),
            Output("trace", "trace-event", 1, isIgnorable: true),
        ];

    /// <summary>Builds the result ports of the rich fixture specification.</summary>
    /// <returns>One result port.</returns>
    private static ResultPortSpecification[] MapperResults() =>
        [ResultPortSpecification.Create(PortId.Create("count"), Contract("counter-result", 1))];

    /// <summary>Builds an input port specification.</summary>
    /// <param name="port">The port name.</param>
    /// <param name="contract">The element contract identifier text.</param>
    /// <param name="majorVersion">The element contract major version.</param>
    /// <param name="isOptional">Whether the port may be left unconnected.</param>
    /// <returns>The port specification.</returns>
    private static InputPortSpecification Input(
        string port,
        string contract,
        int majorVersion,
        bool isOptional) =>
        InputPortSpecification.Create(PortId.Create(port), Contract(contract, majorVersion), isOptional);

    /// <summary>Builds an output port specification.</summary>
    /// <param name="port">The port name.</param>
    /// <param name="contract">The element contract identifier text.</param>
    /// <param name="majorVersion">The element contract major version.</param>
    /// <param name="isIgnorable">Whether the port may be left unconnected.</param>
    /// <returns>The port specification.</returns>
    private static OutputPortSpecification Output(
        string port,
        string contract,
        int majorVersion,
        bool isIgnorable) =>
        OutputPortSpecification.Create(PortId.Create(port), Contract(contract, majorVersion), isIgnorable);

    /// <summary>Builds a contract reference from its two components.</summary>
    /// <param name="contract">The contract identifier text.</param>
    /// <param name="majorVersion">The compatibility major version.</param>
    /// <returns>The contract reference.</returns>
    private static ContractReference Contract(string contract, int majorVersion) =>
        ContractReference.Create(ContractId.Create(contract), majorVersion);

    /// <summary>A validator that rejects every payload with one fixed fragment.</summary>
    /// <param name="fragment">The fragment this validator returns.</param>
    private sealed class FixtureValidator(string fragment) : IStageParameterValidator
    {
        /// <inheritdoc/>
        public IReadOnlyList<string> Validate(CanonicalJsonValue parameters) => [fragment];
    }
}
