using Orleans.Dataflow.Definition;
using Orleans.Dataflow.Identity;
using Orleans.Dataflow.Serialization;

namespace Orleans.Dataflow.Tests.Serialization;

/// <summary>
/// The documents the golden fixtures under <c>tests/Orleans.Dataflow.Tests/Fixtures</c> pin.
/// </summary>
/// <remarks>
/// <para>
/// A golden test is only worth its bytes when the document it compares against is built here, in code,
/// rather than decoded from the fixture it is checking. Building it in code is what makes a change in the
/// writer show up as a byte difference instead of quietly changing both sides of the comparison.
/// </para>
/// <para>
/// The fixture files themselves were generated by serializing exactly these documents, so a deliberate
/// format change is a deliberate regeneration of the files, reviewed as a diff.
/// </para>
/// </remarks>
internal static class FixtureGraphs
{
    /// <summary>The file name of the minimal fixture.</summary>
    internal const string MinimalFileName = "minimal-graph.v1.json";

    /// <summary>The file name of the representative fixture.</summary>
    internal const string RepresentativeFileName = "representative-graph.v1.json";

    /// <summary>The file name of the fixture written under a format version this library does not read.</summary>
    internal const string UnknownVersionFileName = "unknown-version.v2.json";

    /// <summary>
    /// Builds the smallest document the model admits: one node, and nothing else.
    /// </summary>
    /// <returns>The minimal fixture document.</returns>
    /// <remarks>
    /// The empty collections are the point of this fixture. They pin that an empty array is written as an
    /// empty array rather than omitted, and that a node without an execution policy writes two explicit
    /// nulls.
    /// </remarks>
    internal static GraphDocument Minimal() =>
        GraphDocument.Create(
            GraphId.Create("minimal-graph"),
            GraphRevision.Create(1),
            [],
            [
                StageNode.Create(
                    NodeId.Create("source"),
                    StageRef.Create(ProviderId.Create("orleans-core"), StageId.Create("from-source"), 1),
                    ContractReference.Create(ContractId.Create("source-parameters"), 1),
                    CanonicalJsonValue.Parse("""{"capacity":16}""")),
            ],
            [],
            []);

    /// <summary>
    /// Builds a document that exercises every part of the envelope.
    /// </summary>
    /// <returns>The representative fixture document.</returns>
    /// <remarks>
    /// The document carries a declared capability, a hierarchical node identifier, three nodes of which
    /// exactly one declares an execution policy, two edges, two result slots with distinct producers, a
    /// stage reference and a contract reference with major versions above one, and a payload string with
    /// a non-ASCII character that must survive as raw UTF-8 rather than as an escape.
    /// </remarks>
    internal static GraphDocument Representative() =>
        GraphDocument.Create(
            GraphId.Create("orders-import"),
            GraphRevision.Create(7),
            [CapabilityToken.Nondeployable],
            [Reader(), Mapper(), Writer()],
            [
                GraphEdge.Create(Port("reader", "out"), Port("stage/mapper", "in")),
                GraphEdge.Create(Port("stage/mapper", "out"), Port("writer", "in")),
            ],
            [
                ResultSlotDefinition.Create(
                    ResultSlotId.Create("imported-count"),
                    ContractReference.Create(ContractId.Create("counter-result"), 1),
                    Port("writer", "result")),
                ResultSlotDefinition.Create(
                    ResultSlotId.Create("rejected-count"),
                    ContractReference.Create(ContractId.Create("counter-result"), 1),
                    Port("stage/mapper", "rejected")),
            ]);

    /// <summary>
    /// Builds the representative document from inputs supplied in a different order.
    /// </summary>
    /// <returns>A document equal to <see cref="Representative"/>.</returns>
    /// <remarks>
    /// Canonical order is a property of the document, not of the caller's arguments. Serializing this
    /// document and the one above must produce the same bytes, or order insensitivity stops where
    /// serialization begins.
    /// </remarks>
    internal static GraphDocument RepresentativeFromPermutedInputs() =>
        GraphDocument.Create(
            GraphId.Create("orders-import"),
            GraphRevision.Create(7),
            [CapabilityToken.Nondeployable],
            [Writer(), Mapper(), Reader()],
            [
                GraphEdge.Create(Port("stage/mapper", "out"), Port("writer", "in")),
                GraphEdge.Create(Port("reader", "out"), Port("stage/mapper", "in")),
            ],
            [
                ResultSlotDefinition.Create(
                    ResultSlotId.Create("rejected-count"),
                    ContractReference.Create(ContractId.Create("counter-result"), 1),
                    Port("stage/mapper", "rejected")),
                ResultSlotDefinition.Create(
                    ResultSlotId.Create("imported-count"),
                    ContractReference.Create(ContractId.Create("counter-result"), 1),
                    Port("writer", "result")),
            ]);

    /// <summary>Builds the source node of the representative document.</summary>
    /// <returns>A node without an execution policy.</returns>
    private static StageNode Reader() =>
        StageNode.Create(
            NodeId.Create("reader"),
            StageRef.Create(ProviderId.Create("orleans-core"), StageId.Create("from-source"), 1),
            ContractReference.Create(ContractId.Create("source-parameters"), 1),
            CanonicalJsonValue.Parse("""{"batchSize":500,"path":"/data/orders"}"""));

    /// <summary>Builds the mapping node of the representative document.</summary>
    /// <returns>A node with a hierarchical identifier and an execution policy.</returns>
    private static StageNode Mapper() =>
        StageNode.Create(
            NodeId.Parse("stage/mapper"),
            StageRef.Create(ProviderId.Create("orleans-core"), StageId.Create("map-async"), 2),
            ContractReference.Create(ContractId.Create("map-parameters"), 3),
            CanonicalJsonValue.Parse("""{"parallelism":4,"projection":"order-summary"}"""),
            ContractReference.Create(ContractId.Create("retry-policy"), 1),
            CanonicalJsonValue.Parse("""{"backoffMilliseconds":250,"maxAttempts":5}"""));

    /// <summary>Builds the sink node of the representative document.</summary>
    /// <returns>A node whose parameter payload carries a non-ASCII string.</returns>
    /// <remarks>
    /// The non-ASCII character is written as a C# escape so that this file stays ASCII and no editor or
    /// tool can change what the test means by re-encoding it. The canonical form of the payload carries
    /// the character as raw UTF-8, which is what the fixture pins.
    /// </remarks>
    private static StageNode Writer() =>
        StageNode.Create(
            NodeId.Create("writer"),
            StageRef.Create(ProviderId.Create("contoso-sinks"), StageId.Create("to-table"), 1),
            ContractReference.Create(ContractId.Create("table-sink-parameters"), 1),
            CanonicalJsonValue.Parse("{\"table\":\"orders\",\"tenant\":\"kontor-n\u00fcrnberg\"}"));

    /// <summary>Builds a port address from its two identifier texts.</summary>
    /// <param name="node">The node identifier path.</param>
    /// <param name="port">The port identifier segment.</param>
    /// <returns>The port address.</returns>
    private static PortAddress Port(string node, string port) =>
        PortAddress.Create(NodeId.Parse(node), PortId.Create(port));
}
